### PR TITLE
Setup Travis to trigger docker builds and DockerHub & Heroku deploys

### PR DESCRIPTION
**Pull request by mpacer**
This creates the necessary infrastructure to automatically build a docker image with every PR that comes in.

Additionally, once the PR is merged to master, travis should automatically deploy the resulting images to both DockerHub and Heroku.

### CODE REVIEW

**Comment by mpacer** [comment]
@stefanv, it'd be great if you would take a look at this when you have a chance!

**Comment by stefanv** [comment]
This looks great, thanks @mpacer!

**Comment by cbcunc** [comment]
*If* we aren't deploying on Heroku going foward, is this still a thing? Calling out @deniederhut.

**Comment by stefanv** [comment]
If you are not deploying to Heroku, you probably want to check what mechanism you *will* be using.  If it is still container based, then some of this can be re-used.

**Comment by stefanv** [comment]
If you are not deploying to Heroku, you probably want to check what mechanism you *will* be using.  If it is still container based, then some of this can be re-used.

**Comment by deniederhut** [comment]
Having the images automatically rebuilt could be nice, so probably everything except the heroku specific would still be useful to have.

**Comment by cbcunc** [comment]
No longer a thing.

**Pull request closed without merging**
