### PR TITLE
Py3 convert

### PR DESCRIPTION
**Pull request by mpacer**
This should address the problems with spacing that some people are having. 

@stefanv would you take a look at this and give me a heads up if there's anything that you see that is questionable? I'll merge later tonight and restart the build server.

### CODE REVIEW

**Comment by mpacer** [comment]
Note this is a top priority as fixing `IEEEtran.cls` will fix some of the currently failing builds e.g., https://github.com/scipy-conference/scipy_proceedings/pull/291

**Comment by stefanv** [comment]
This looks OK; but very little seems related to IEEEtran?

**Comment by mpacer** [comment]
It was other stuff that I had on the or. If it were only the IEEEtran stuff I would have just merged it. I can cherry pick and make it a new pr but i figured that since this stuff has been working for me locally for the past month it would be ok to merge.

**Comment by stefanv** [comment]
Go ahead!

**Pull request merged**
