### PR TITLE
BUG: stop keying papers with enumerate

### LINKED ISSUE #18: When a PR is closed the indices break.
When a PR is closed, the code seems to detect this and reindex everything, but then it does not propagate that to what is displayed in the html view.

### PR DESCRIPTION
**Pull request by deniederhut**
procbuild assigns a unique identifier to each paper that it uses
to retrieve the paper status and pdf. Currently, this is done
by enumerating open PRs, which works fine until a PR is opened
or closed, at which point all of the IDs are off by one. This
commit replaces the integer keys with one composed of the user
and branch name, which is hopefully close enough to unique.
Closes #18.

Note: the commit is not as large as the diff seems to indicate.
A lot of the file changes are from my editor auto-deleting the
trailing whitespace on a bunch of lines.

### CODE REVIEW

**Comment by deniederhut** [comment]
@cbcunc this is ready for a second look

**Comment by cbcunc** [comment]
@deniederhut  Thanks! I'm glad you caught this. I'll pull your branch again and retest soon if not today.

**Comment by cbcunc** [comment]
This works.

**Comment by cbcunc** [comment]
@deniederhut I do not seem to have permissions to merge this after a successful test. I'd like to pull it into the RENCI procbuild.

**Comment by cbcunc** [comment]
@deniederhut Problem seems to be normal proceedings team members have only read access to the procbuild repo (while having admin on all the eight other repos to which the team has privileges). Four of the members (but not me) are listed as maintainers, which gives them elevated privileges above read.

**Comment by stefanv** [comment]
@cbcunc I'll fix the permissions.

**Comment by cbcunc** [comment]
Deployed to RENCI instance yesterday.

**Pull request merged**
